server:
  port: 8080
#  servlet:
#    contextPath: /api
 
spring:
  jpa:
    hibernate:
      ddl-auto: create
      
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root    

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8080/authen/oauth/check_token/
      