server:
  port: 9000

spring:
  security:
    user:
      name: pokky
      password: password

security:
  oauth2:
    client:
      client-id: clientId
      client-secret: clientSecret
      authorized-grant-types: authorization_code, refresh_token, password
      scope: openid